### ISSUE TITLE
Ask about Template files

### ISSUE THREAD

**Issue by karfianto** [vladimirok5959/golang-fave#4]
Hi,

I just tried it.

What's the different between templates in host/localhost/template and assets/template

Are all assets included in the compiled binary file?

**Comment by vladimirok5959** [comment]
So, you can't use front-end without host template files, CMS will print you 500 error page.

> What's the different between templates in host/localhost/template and assets/template

`assets/template` contains the same, original template files from `host/localhost/template`. Actually if you just install CMS, then `host/localhost/template` and `assets/template` are the same. But `assets/template` will never be changed by user (by editing files or from control panel).

> Are all assets included in the compiled binary file?

Yes, `assets/template` used for including to binary file.

Why? If you something broke in control panel, in `Template` section, you can restore any template (or all together) by one button. It's more for users and maybe I will extend `Template` section by backups.

![Screenshot from 2019-09-18 13-38-24](https://user-images.githubusercontent.com/9799858/65141963-59ac9c00-da1a-11e9-8515-a44c1ac2723c.png)

**Comment by vladimirok5959** [comment]
Sorry, I will close this issue. Feel free to open any issues/PRs.
