### ISSUE TITLE
How to change the bootstrap template to sb-admin-2

### ISSUE THREAD

**Issue by karfianto** [vladimirok5959/golang-fave#5]
Hi,

Another question, how to change the template to [sb-admin-2](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2) 

I've installed it successfully and it is placed in \golang-fave\node_modules\startbootstrap-sb-admin-2

Thanks again

**Comment by karfianto** [comment]
When I search the structure, bootstrap is located in `golang-server-bootstrap/bootstrap`

I've tried to replace the variables
`resource_bootstrap_js` and `resource_bootstrap_css` but still no luck.

**Comment by vladimirok5959** [comment]
Bootstrap is mounted to binary too, both, CSS and JS.

It will be not easy.
`golang-fave/node_modules` used only for Cypress testing and nothing more.

To change control panel template you needs to modify this files:
`golang-fave/assets/cp.styles.css`, `golang-fave/assets/cp.scripts.js`. Then compile it to `golang-fave/assets/cp.styles.css.go` and `golang-fave/assets/cp.scripts.js.go`, and then re-compile application.

This files actually is sources for development:
```
golang-fave/assets/cp.styles.css
golang-fave/assets/cp.scripts.js
```

This files used in real-time:
```
golang-fave/assets/cp.styles.css.go
golang-fave/assets/cp.scripts.js.go
```

They contains all CSS and JS from different libs to reduce or http requests. Bootstarp here too.

**Comment by vladimirok5959** [comment]
Or you can just replace JS src here: https://github.com/vladimirok5959/golang-fave/blob/master/assets/tmpl.cp.base.html#L18

This var generate here: https://github.com/vladimirok5959/golang-fave/blob/master/utils/utils.go#L130

If you don't want to use it as mounted resource.

**Comment by karfianto** [comment]
Have tried but still no luck. Is it possible to provide a branch with bootstrap template example?

**Comment by vladimirok5959** [comment]
Sorry, this is hobby project for me, my wife and some several peoples web-sites. Currently I am woks at full-stuck time. Can work on this only on holidays or after work if I have some energy... So, if it will be still actually for you, I will make some example after 4-5 hours.

Don't forgot to recompile app after some changes, it's not like PHP. Take a look here: https://github.com/vladimirok5959/golang-fave/blob/master/assets/tmpl.cp.base.go , this is compiled HTML file, if you edit just this file https://github.com/vladimirok5959/golang-fave/blob/master/assets/tmpl.cp.base.html it will not works. Probably needs to add some auto-compilation in Makefile...

**Comment by vladimirok5959** [comment]
Branch: `temp/how-to-change-control-panel-css-js`
You can review changes here: https://github.com/vladimirok5959/golang-fave/commit/c86863a7bfc5d437f94db58d2495f8862a875462

File `assets/tmpl.cp.base.go` just unwrapped, actually I added only 2 lines:
```
<link rel="stylesheet" href="/assets/cp/sb-admin-2/styles.css">
<script src="/assets/cp/sb-admin-2/scripts.js"></script>
```

Run `make` in root project folder, and you will be able to access new files by links:
```
http://localhost:8080/assets/cp/sb-admin-2/styles.css
http://localhost:8080/assets/cp/sb-admin-2/scripts.js
```

BTW: I review, SB Admin 2 demo, it's not usable by mobile phones where screen width is 240-280 pixels. It's will be a hard work to rework all CP for new components. Popup messages, dialogs, ajax actions, places for images and etc.. I don't see a reason for this. Looks like there are only CSS is used. So, if something is needs, you can just copy to main control panel CSS file and all... (this is how I would do).

CP forms HTML code here:
```
engine/builder/*.go
```

CP base HTML code here:
```
assets/tmpl.cp.base.html
assets/tmpl.cp.base.go
```

**Comment by karfianto** [comment]
Hi, @vladimirok5959  that's cool and very useful.

Really appreciate it.
